.TH CALC 1 "Apr 2024" "Version 1.0"
.SH NAME
calc \- a minimalist calculator
.SH SYNOPSIS
.B calc [number1 [+ - (* or x) % /] number2]
.SH DESCRIPTION
.B calc
read two numbers as arguments, operator between them and calculate it.

.SH OPTIONS
Numbers and operator is options
.SH AUTHOR
.IR calc
was wriiten by Bogdan. More at <https://github.com/snowsova/calc>


